org: camerontheross
app: serverless-todo
service: serverless-todo
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs22.x

  environment:
    DYNAMODB_TODO_TABLE: ${self:service}-todoList-${sls:stage}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:Query*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-todoList-${sls:stage}

package:
  individually: true

functions:
  createTask:
    handler: src/createTask.createTask
    events:
      - httpApi:
          path: /createTask
          method: post
  getAllTasks:
    handler: src/getAllTasks.getAllTasks
    events:
      - httpApi:
          path: /
          method: get

  getTasksByStatus:
    handler: src/getTasksByStatus.getTasksByStatus
    events:
      - httpApi:
          path: /status/{status}
          method: get

resources:
  Resources:
    TodoListTable:
      Type: AWS::DynamoDB::Table

      Properties:
        AttributeDefinitions:
          - AttributeName: todoId
            AttributeType: N
          - AttributeName: status
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: todoId
            KeyType: RANGE
        TableName: ${self:service}-todoList-${sls:stage}
